spring.application.name=FinanziAppBackend
# 1. Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finanziapp_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Creación y actualización automática de la BD
spring.jpa.hibernate.ddl-auto=update

# 3. Dialecto de PostgreSQL para Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Ver en consola del backend las sentencias SQL que Hibernate ejecuta
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true